/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userpack;

import DB.DBConnection;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class userpage extends javax.swing.JFrame {
String uid="Shivam";
    /**
     * Creates new form userpage
     */
    public userpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        userpage = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        dropgym = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        changepassword = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        persondetail = new javax.swing.JInternalFrame();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField40 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        persontimeing = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        dropform = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        purchaseequipment = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        equipmentdetail = new javax.swing.JInternalFrame();
        jLabel35 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        attendance = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        attendlist = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpage.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        userpage.setTitle("USER PAGE");
        userpage.setVisible(true);
        userpage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropgym.setBackground(new java.awt.Color(0, 0, 0));
        dropgym.setClosable(true);
        dropgym.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        dropgym.setIconifiable(true);
        dropgym.setMaximizable(true);
        dropgym.setResizable(true);
        dropgym.setTitle("DROP GYM");
        dropgym.setVisible(false);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/GYM_Dumbells.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 51));
        jLabel15.setText("PERSON NAME");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout dropgymLayout = new javax.swing.GroupLayout(dropgym.getContentPane());
        dropgym.getContentPane().setLayout(dropgymLayout);
        dropgymLayout.setHorizontalGroup(
            dropgymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropgymLayout.createSequentialGroup()
                .addGroup(dropgymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dropgymLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel15)
                        .addGap(44, 44, 44)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropgymLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dropgymLayout.setVerticalGroup(
            dropgymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropgymLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dropgymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(dropgym, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 750, 490));

        changepassword.setClosable(true);
        changepassword.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        changepassword.setIconifiable(true);
        changepassword.setMaximizable(true);
        changepassword.setResizable(true);
        changepassword.setTitle("CHANGE PASSWORD");
        changepassword.setVisible(false);
        changepassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/images.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel3.setText("Old Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setText("New Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 170, 30));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, 30));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 370, 200));

        changepassword.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 300));

        jPanel1.add(changepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 390, 330));

        persondetail.setClosable(true);
        persondetail.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        persondetail.setIconifiable(true);
        persondetail.setMaximizable(true);
        persondetail.setResizable(true);
        persondetail.setTitle("PERSON DETAIL");
        persondetail.setVisible(false);
        persondetail.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StmtApps/BENEFIT-BANNER2.jpg"))); // NOI18N
        persondetail.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 80));

        jLabel36.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel36.setText("NAME");
        persondetail.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel38.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel38.setText("FATHER'S NAME");
        persondetail.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel39.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel39.setText("NATIONALITY");
        persondetail.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel40.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel40.setText("MOBILE NUMBER");
        persondetail.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel41.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel41.setText("EMAIL ADDRESS");
        persondetail.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel42.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel42.setText("SEX");
        persondetail.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel43.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel43.setText("MARITAL STATUS");
        persondetail.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel44.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel44.setText("DATE OF BIRTH");
        persondetail.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel45.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel45.setText("HEIGHT");
        persondetail.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel46.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel46.setText("WEIGHT");
        persondetail.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel47.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel47.setText("IDENTIFICATION MARK");
        persondetail.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel48.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel48.setText("ADDRESS");
        persondetail.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        persondetail.getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 400, 30));
        persondetail.getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 400, -1));
        persondetail.getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 400, -1));
        persondetail.getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 400, -1));
        persondetail.getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 400, -1));

        jRadioButton9.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jRadioButton9.setText("MALE");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jRadioButton10.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jRadioButton10.setText("FEMALE");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jRadioButton11.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jRadioButton11.setText("SINGLE");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jRadioButton12.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jRadioButton12.setText("MARRID");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));
        persondetail.getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 140, -1));
        persondetail.getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 140, -1));
        persondetail.getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 130, -1));
        persondetail.getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 400, -1));

        jButton13.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        jButton13.setText("SUBMIT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jButton14.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        jButton14.setText("ALLOT TIME");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel12.setText("CHARGES FEE");
        persondetail.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));
        persondetail.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 130, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel13.setText("CONTRACT");
        persondetail.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "2 month", "5 month", "7 month", "10 month", "12 month" }));
        persondetail.getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 400, 30));

        jButton4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        persondetail.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));
        persondetail.getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 400, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        persondetail.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel1.add(persondetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 820, 520));

        persontimeing.setClosable(true);
        persontimeing.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        persontimeing.setIconifiable(true);
        persontimeing.setMaximizable(true);
        persontimeing.setResizable(true);
        persontimeing.setTitle("PERON TIMIENG");
        persontimeing.setVisible(false);
        persontimeing.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StmtApps/garage-gym-shopnow.jpg"))); // NOI18N
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 567, -1));

        jLabel50.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel50.setText("NAME");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 124, -1, -1));

        jLabel51.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel51.setText("FATHER'S NAME");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 167, -1, -1));

        jLabel52.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel52.setText("MOBILE NO");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, -1, -1));

        jLabel53.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel53.setText("BATCH TIMING");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 268, -1, -1));

        jLabel54.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel54.setText("BATCH NUMBER");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 315, -1, -1));

        jTextField27.setEditable(false);
        jPanel6.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 121, 200, -1));

        jTextField28.setEditable(false);
        jPanel6.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 167, 200, -1));

        jTextField29.setEditable(false);
        jPanel6.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 216, 200, -1));
        jPanel6.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 268, 200, -1));
        jPanel6.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 315, 200, -1));

        jButton15.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jButton15.setText("SUBMIT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jButton16.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jButton16.setText("CANCEL");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        persontimeing.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 529, 395));

        jPanel1.add(persontimeing, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 500, 410));

        dropform.setClosable(true);
        dropform.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        dropform.setTitle("PERSON DROP GYM FORM");
        dropform.setVisible(false);
        dropform.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(51, 0, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 153));
        jLabel16.setText("PERSON DROP GYM FORM");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jPanel11.setBackground(new java.awt.Color(255, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel17.setText("NAME");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel18.setText("FATHER'S NAME");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel19.setText("MOBILE NUMBER");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel20.setText("EMAIL ID");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel21.setText("BEFORE HEIGHT");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel22.setText("AFTER HEIGHT");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel23.setText("BEFORE WEIGHT");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel24.setText("AFTER WEIGHT");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel25.setText("WEIGHT CHANGEMENT");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel26.setText("HEIGHT CHANGEMENT");
        jLabel26.setToolTipText("");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel27.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel27.setText("DATE OF BIRTH");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel28.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel28.setText("CONTRACT");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel29.setText("SEX");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel30.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel30.setText("MARITAL");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel31.setText("ADDRESS");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel11.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 260, -1));
        jPanel11.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 260, -1));
        jPanel11.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 260, -1));
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 260, -1));
        jPanel11.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 260, -1));
        jPanel11.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 600, 70));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 280, -1));
        jPanel11.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 280, -1));
        jPanel11.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 280, -1));
        jPanel11.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 280, -1));
        jPanel11.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 280, -1));
        jPanel11.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 280, -1));

        jRadioButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jRadioButton3.setText("SINGLE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jRadioButton4.setText("MARRID");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel11.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("CANCEL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 260, -1));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 410));

        dropform.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 994, 450));

        jPanel1.add(dropform, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 1010, 480));

        purchaseequipment.setClosable(true);
        purchaseequipment.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        purchaseequipment.setTitle("PURCHASE EQUIPMENT");
        purchaseequipment.setVisible(false);
        purchaseequipment.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setText("PURCHASE EQUIPMENT");
        purchaseequipment.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setText("EQUIPMENT NAME");
        purchaseequipment.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setText("EQUIPMENT COST");
        purchaseequipment.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel32.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel32.setText("MODEL NO");
        purchaseequipment.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel33.setText("QUANTITY");
        purchaseequipment.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel34.setText("DISCRIPTION");
        purchaseequipment.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        purchaseequipment.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jButton5.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        purchaseequipment.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));
        purchaseequipment.getContentPane().add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 220, 30));
        purchaseequipment.getContentPane().add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 30));
        purchaseequipment.getContentPane().add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 220, 30));
        purchaseequipment.getContentPane().add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 30));
        purchaseequipment.getContentPane().add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 220, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/global2.jpg"))); // NOI18N
        purchaseequipment.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        jPanel1.add(purchaseequipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 660, -1));

        equipmentdetail.setClosable(true);
        equipmentdetail.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        equipmentdetail.setTitle("DETAIL EQUIPMENT");
        equipmentdetail.setVisible(false);
        equipmentdetail.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 51, 51));
        jLabel35.setText("DETAIL OF  EQUIPMENT");
        equipmentdetail.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, -1, -1));

        jLabel56.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel56.setText("Equipment Name");
        equipmentdetail.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jTextField39.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField39KeyReleased(evt);
            }
        });
        equipmentdetail.getContentPane().add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 320, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        equipmentdetail.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 730, 380));

        jPanel1.add(equipmentdetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 740, 520));

        attendance.setClosable(true);
        attendance.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        attendance.setTitle("ATTENDANCE");
        attendance.setVisible(false);
        attendance.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("ATTENDANCE");
        attendance.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setText("Enter the mobile number");
        attendance.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel55.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel55.setText("Enter the name");
        attendance.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel58.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel58.setText("Status");
        attendance.getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        attendance.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 230, 30));
        attendance.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 230, 30));

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setText("Present");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        attendance.getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton6.setText("Absent");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        attendance.getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        attendance.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/112.jpg"))); // NOI18N
        attendance.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 560, -1));

        jPanel1.add(attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 510, 360));

        attendlist.setBackground(new java.awt.Color(255, 51, 51));
        attendlist.setClosable(true);
        attendlist.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        attendlist.setTitle("ATTEND LIST");
        attendlist.setVisible(false);
        attendlist.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 0, 0));
        jLabel60.setText("ATTENDANCE LIST");
        jPanel4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 12, -1, 30));

        attendlist.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        jLabel61.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel61.setText("Person name");
        attendlist.getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jTextField42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField42KeyReleased(evt);
            }
        });
        attendlist.getContentPane().add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 290, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        attendlist.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 930, 390));

        jPanel1.add(attendlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 940, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/user2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 1930, 930));

        userpage.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 730));

        jMenu1.setText("ENTRY");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem4.setText("ADDMISION");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("ATTENDANCE");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem3.setText("Attendance list");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem8.setText("Attendance");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("GYM EQUIPMENT");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem5.setText("purchase equipment");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem6.setText("detail");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("DROP GYM");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem2.setText("Drop gym");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem7.setText("dropform");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("ACCOUNT");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpack/111.png"))); // NOI18N
        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        userpage.setJMenuBar(jMenuBar1);

        jDesktopPane1.add(userpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
changepassword.setVisible(true); 


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
attendlist.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
    persondetail.setVisible(false);
        persontimeing.setVisible(true);
        jTextField27.setText(names);
jTextField28.setText(fname);
jTextField29.setText(mno);// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    persondetail.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
jRadioButton9.setSelected(true);        // TODO add your handling code here:
jRadioButton10.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
jRadioButton10.setSelected(true);        // TODO add your handling code here:
jRadioButton9.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
jRadioButton11.setSelected(true);        // TODO add your handling code here:
jRadioButton12.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
jRadioButton12.setSelected(true);        // TODO add your handling code here:
jRadioButton11.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed
String names="";
String fname="";
String mno="";
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
try{

DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("insert into persondetail(name,father,nationality,mobile,email,sex,merital,dob,chargesfee,height,weight,id_mark,address,contract)"+"values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

db.pstmt.setString(1,jTextField18.getText());
db.pstmt.setString(2,jTextField19.getText());
db.pstmt.setString(3,jTextField20.getText());
db.pstmt.setString(4,jTextField21.getText());
db.pstmt.setString(5,jTextField22.getText());
//
String sex="";
if(jRadioButton9.isSelected())
{
sex="Male";    
}
if(jRadioButton10.isSelected())
{
sex="Female";    
}        
db.pstmt.setString(6,sex); 
String marital="";
if(jRadioButton11.isSelected())
{
marital="Single";    
}
if(jRadioButton12.isSelected())
{
marital="Marrid";    
}
db.pstmt.setString(7,marital); 
db.pstmt.setString(8,jTextField23.getText());
db.pstmt.setString(9,jTextField5.getText());
db.pstmt.setString(10,jTextField24.getText());
db.pstmt.setString(11,jTextField25.getText());
db.pstmt.setString(12,jTextField26.getText());
db.pstmt.setString(13,jTextField40.getText());
String cont="";
db.pstmt.setString(14,cont);
 
db.pstmt.setString(14,(String)jComboBox4.getSelectedItem());


int i=db.pstmt.executeUpdate();
if(i>0)
{
    JOptionPane.showMessageDialog(this,"submitted Successfully");
    names=jTextField18.getText();
    fname=jTextField19.getText();
      mno=jTextField21.getText();
    jTextField18.setText("");
    jTextField19.setText("");
    jTextField20.setText("");
    jTextField21.setText("");
    jTextField22.setText("");
     jTextField23.setText("");
     jTextField5.setText("");
      jTextField24.setText("");
     jTextField25.setText("");
     jTextField26.setText("");
     jTextField40.setText("");
     jComboBox4.setSelectedItem("");
}
else
{
    JOptionPane.showMessageDialog(this,"cannot register");
}

db.con.close();
db.pstmt.close();
}
catch(Exception e)
{
    e.printStackTrace();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
     try{
if(jTextField27.getText().equals("")||jTextField28.getText().equals("")||jTextField29.getText().equals("")||jTextField30.getText().equals("")||jTextField31.getText().equals("")){
    JOptionPane.showMessageDialog(this,"Invalid value");
    
}
else{
    
DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("insert into persontiming"+"(name,father,mobile,batchtiming,batchno)"+"values(?,?,?,?,?)");

db.pstmt.setString(1,jTextField27.getText());
db.pstmt.setString(2,jTextField28.getText());
db.pstmt.setString(3,jTextField29.getText());
db.pstmt.setString(4,jTextField30.getText());
db.pstmt.setString(5,jTextField31.getText());
int i=db.pstmt.executeUpdate();
if(i>0)
{
    
    jTextField27.setText("");
    jTextField28.setText("");
    jTextField29.setText("");
    jTextField30.setText("");
    jTextField31.setText("");
JOptionPane.showMessageDialog(this,"submitted Successfully"); 
}
else
{
    JOptionPane.showMessageDialog(this,"cannot submitted");
}

db.con.close();
db.pstmt.close();
}}
catch(Exception e)
{
    e.printStackTrace();
}     // TODO add your handling code here:
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
changepassword.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
persondetail.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
persondetail.setVisible(true);
        persontimeing.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
dropgym.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
purchaseequipment.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("insert into pureqp"+"(eqp_name,eqp_cost,model_no,quantity,discription)"+"values(?,?,?,?,?)");

db.pstmt.setString(1,jTextField34.getText());
db.pstmt.setString(2,jTextField35.getText());
db.pstmt.setString(3,jTextField36.getText());
db.pstmt.setString(4,jTextField37.getText());
db.pstmt.setString(5,jTextField38.getText());
int i=db.pstmt.executeUpdate();
if(i>0)
{
    JOptionPane.showMessageDialog(this,"Successfully added");
    jTextField34.setText("");
    jTextField35.setText("");
    jTextField36.setText("");
    jTextField37.setText("");
    jTextField38.setText("");
    
}
else
{
    JOptionPane.showMessageDialog(this,"ERROR!!!!!!!!!!!");
}

db.con.close();
db.pstmt.close();}
catch(Exception e)
{
    e.printStackTrace();
}        // TODO add your handling code         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
purchaseequipment.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTextField39KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField39KeyReleased
   equipmentdetail.setVisible(true);
try{
      DBConnection db=new DBConnection();
    
      Vector<Vector<String>>data=new Vector<Vector<String>>();
         data.removeAllElements();
      Vector<String>header=new Vector<String>();
      header.removeAllElements();
      header.add("Equipment name");
      header.add("Equipment cost");
      header.add("Model number");
      header.add("quantity");
      header.add("Discription");
      String str=jTextField39.getText();
      db.stmt=db.con.createStatement();
      db.rst=db.stmt.executeQuery("select eqp_name,eqp_cost,model_no,quantity,discription from pureqp where eqp_name like\'"+str+"%\'order by eqp_name");
      while(db.rst.next())
      {   Vector<String>data1=new Vector<String>();
          data1.add(db.rst.getString(1));
          data1.add(db.rst.getString(2));
          data1.add(db.rst.getString(3));
          data1.add(db.rst.getString(4));
          data1.add(db.rst.getString(5));
          
             data1.add("\n");
          data.add(data1);
      }
      jTable3.setModel(new javax.swing.table.DefaultTableModel(data,header));
      
      db.con.close();
      db.rst.close();
      db.stmt.close();
      }
      catch(Exception e)
      {
e.printStackTrace();
      }                // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39KeyReleased

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
equipmentdetail.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   dropform.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try{
DBConnection db=new DBConnection();
  String nname=(String)jComboBox1.getSelectedItem();
    //  db.pstmt=db.con.prepareStatement("select quantity from medicinepur where medicine_name='"+nname+"'");
db.pstmt=db.con.prepareStatement("insert into dropgym(name,father,mobile,email,bweight,aweight,bheight,aheight,weightcha,heightcha,dob,contract,sex,marital,address) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
 db.pstmt.setString(1,nname);
//db.pstmt.setString(1,(String)jComboBox1.getSelectedItem());
db.pstmt.setString(2,jTextField14.getText());
db.pstmt.setString(3,jTextField8.getText());
db.pstmt.setString(4,jTextField15.getText());
db.pstmt.setString(5,jTextField9.getText());
db.pstmt.setString(6,jTextField16.getText());
db.pstmt.setString(7,jTextField10.getText());
db.pstmt.setString(8,jTextField17.getText());
db.pstmt.setString(9,jTextField11.getText());
db.pstmt.setString(10,jTextField32.getText());
db.pstmt.setString(11,jTextField12.getText());
db.pstmt.setString(12,jTextField33.getText());
String sex="";
if(jRadioButton1.isSelected())
{
sex="Male";    
}
if(jRadioButton2.isSelected())
{
sex="Female";    
}        
db.pstmt.setString(13,sex); 
String marital="";
if(jRadioButton3.isSelected())
{
marital="Single";    
}
if(jRadioButton4.isSelected())
{
marital="Marrid";    
}
db.pstmt.setString(14,marital); 
db.pstmt.setString(15,jTextField13.getText());
System.out.print("Shivam");
int i=db.pstmt.executeUpdate();

if(i>0)
{
    JOptionPane.showMessageDialog(this,"submitted Successfully");
    
     
     jTextField8.setText("");
     jTextField9.setText("");
     jTextField10.setText("");
     jTextField11.setText("");
     jTextField12.setText("");
     jTextField13.setText("");
     jTextField14.setText("");
     jTextField15.setText("");
     jTextField16.setText("");
     jTextField17.setText("");
     jTextField32.setText("");
     jTextField33.setText("");

    
}
else
{
    JOptionPane.showMessageDialog(this,"cannot submitted");
}

db.con.close();
db.pstmt.close();
}
catch(Exception e)
{
    e.printStackTrace();
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
String name="";
String faname="";
String mbno="";
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
   dropform.setVisible(true);
System.out.print("a1");
//jComboBox1.removeAllItems();
//jComboBox1.addItem("select");
System.out.print("a2");
try
{
    System.out.print("a3");
DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("select name from persondetail");
db.rst=db.pstmt.executeQuery();
System.out.print("a4");
while(db.rst.next())
{
    System.out.print("a5");
jComboBox1.addItem(db.rst.getString(1));
}
db.con.close();
db.rst.close();
db.pstmt.close();
}
catch(Exception e)
{
    System.out.print("yen");
e.printStackTrace();
}        // TODO add your handling code here:
   
//jTextField14.setText(faname);
//jTextField8.setText(mbno);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed
 
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
try{
DBConnection db=new DBConnection();
String nname=jComboBox1.getSelectedItem().toString();
db.stmt=db.con.createStatement();
db.rst=db.stmt.executeQuery("select father,mobile,email,dob,height,weight,address,contract from persondetail where name='"+nname+"'");
if(db.rst.next())
 {
     jTextField14.setText(db.rst.getString(1));
     jTextField8.setText(db.rst.getString(2));
     jTextField15.setText(db.rst.getString(3));
     jTextField12.setText(db.rst.getString(4));
     jTextField9.setText(db.rst.getString(5));
     jTextField10.setText(db.rst.getString(6));
     jTextField13.setText(db.rst.getString(7));
     jTextField33.setText(db.rst.getString(8));

}
else
{
System.out.println("error");
}
db.con.close();
db.rst.close();

}
catch(Exception e)
{

    e.printStackTrace();
}// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{

DBConnection db=new DBConnection();
db.pstmt=db.con.prepareStatement("insert into attendance(mob,name,status,date) values(?,?,?,curdate())");

db.pstmt.setString(1,jTextField4.getText());
db.pstmt.setString(2,jTextField7.getText());

String status="";
if(jRadioButton5.isSelected())
{
status="present";    
}
if(jRadioButton6.isSelected())
{
status="absent";    
}        
db.pstmt.setString(3,status); 

int i=db.pstmt.executeUpdate();
if(i>0)
{
    JOptionPane.showMessageDialog(this,"submitted Successfully");
    jTextField4.setText("");
    jTextField7.setText("");
      
 }
else
{
    JOptionPane.showMessageDialog(this,"cannot submitted");
}

db.con.close();
db.pstmt.close();
}
catch(Exception e)
{
    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
  jRadioButton5.setSelected(true);        // TODO add your handling code here:
jRadioButton6.setSelected(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
      jRadioButton6.setSelected(true);        // TODO add your handling code here:
jRadioButton5.setSelected(false);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
  attendance.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
      try{
DBConnection db=new DBConnection();
String str=jTextField4.getText();
db.stmt=db.con.createStatement();
db.rst=db.stmt.executeQuery("SELECT * FROM persondetail WHERE mobile='"+str+"' ");
if(db.rst.next())
{
jTextField7.setText(db.rst.getString(1));

}
db.con.close();
db.rst.close();
db.stmt.close();
}

catch(Exception e)
{
e.printStackTrace();
}     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    try{
DBConnection db=new DBConnection();
String str=jTextField4.getText();
db.stmt=db.con.createStatement();
db.rst=db.stmt.executeQuery("SELECT * FROM persondetail WHERE mobile='"+str+"'");
if(db.rst.next())
{
jTextField7.setText(db.rst.getString(1));

}
db.con.close();
db.rst.close();
db.stmt.close();
}

catch(Exception e)
{
e.printStackTrace();
}      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
  jRadioButton1.setSelected(true);        // TODO add your handling code here:
jRadioButton2.setSelected(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    jRadioButton2.setSelected(true);        // TODO add your handling code here:
jRadioButton1.setSelected(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
  jRadioButton3.setSelected(true);        // TODO add your handling code here:
jRadioButton4.setSelected(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
   jRadioButton4.setSelected(true);        // TODO add your handling code here:
jRadioButton3.setSelected(false);     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField42KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField42KeyReleased
    attendlist.setVisible(true);
try{
      DBConnection db=new DBConnection();
    
      Vector<Vector<String>>data=new Vector<Vector<String>>();
         data.removeAllElements();
      Vector<String>header=new Vector<String>();
      header.removeAllElements();
      header.add("date");
      header.add("Person name");
      header.add("Mobile no");
      header.add("status");
      String str=jTextField42.getText();
      db.stmt=db.con.createStatement();
      db.rst=db.stmt.executeQuery("select date,name,mob,status from attendance where name like\'"+str+"%\'order by name ");
      while(db.rst.next())
      {   Vector<String>data1=new Vector<String>();
          data1.add(db.rst.getString(1));
          data1.add(db.rst.getString(2));
          data1.add(db.rst.getString(3));
          data1.add(db.rst.getString(4));
          data1.add("\n");
          data.add(data1);
      }
      jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
      
      db.con.close();
      db.rst.close();
      db.stmt.close();
      }
      catch(Exception e)
      {
e.printStackTrace();
      }             // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        dropgym.setVisible(true);
        try{
            DBConnection db=new DBConnection();

            Vector<Vector<String>>data=new Vector<Vector<String>>();
            data.removeAllElements();
            Vector<String>header=new Vector<String>();
            header.removeAllElements();
            header.add("Person name");
            header.add("Mobile no");
            header.add("Before height");
            header.add("after height");
            header.add("Before weight");
            header.add("after weight");
            header.add("contract");
            header.add("address");
            String str=jTextField6.getText();
            db.stmt=db.con.createStatement();
            db.rst=db.stmt.executeQuery("select name,mobile,bheight,aheight,bweight,aweight,contract,address from dropgym where name like\'"+str+"%\'order by name ");
            while(db.rst.next())
            {   Vector<String>data1=new Vector<String>();
                data1.add(db.rst.getString(1));
                data1.add(db.rst.getString(2));
                data1.add(db.rst.getString(3));
                data1.add(db.rst.getString(4));
                data1.add(db.rst.getString(5));
                data1.add(db.rst.getString(6));
                data1.add(db.rst.getString(7));
                data1.add(db.rst.getString(8));
                //data1.add(db.rst.getString(9));

                data1.add("\n");
                data.add(data1);
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(data,header));

            db.con.close();
            db.rst.close();
            db.stmt.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame attendance;
    private javax.swing.JInternalFrame attendlist;
    private javax.swing.JInternalFrame changepassword;
    private javax.swing.JInternalFrame dropform;
    private javax.swing.JInternalFrame dropgym;
    private javax.swing.JInternalFrame equipmentdetail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JInternalFrame persondetail;
    private javax.swing.JInternalFrame persontimeing;
    private javax.swing.JInternalFrame purchaseequipment;
    private javax.swing.JInternalFrame userpage;
    // End of variables declaration//GEN-END:variables
}
